version: "2"
services:
    brain:
        image: summit_at_sea
        expose:
            - 5000
        devices:
            - "/dev/ttyACM0:/dev/ttyACM0"
        command: ~/catkin_ws/devel/env.sh rosrun openag_brain main -D http://db:5984 -A http://brain:5000 -F /home/pi/openag_2016_summit_at_sea_fixture/summit_at_sea.json --screen
        depends_on:
            - db
        restart: unless-stopped
    db:
        image: dogi/rpi-couchdb
        expose:
            - 5984
        ports:
            - 5984:5984
        restart: unless-stopped
